# Use lightweight Nginx web server
FROM nginx:alpine

# Copy all your website files into the container
COPY . /usr/share/nginx/html

# Expose port 80 so AWS can serve the site
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
